"""
Formal Security Analysis — Lemma 1: S-Box Indistinguishability
================================================================

LEMMA 1. The family of S-boxes generated by BAB64's Fisher-Yates
construction (seeded by SHA-256(image || b'sbox')) is computationally
indistinguishable from the uniform distribution on permutations of
[0..255].

PROOF METHOD. For each statistical criterion, we compute the test
statistic on both:
  (A) BAB64 S-boxes — generated by the actual construction
  (B) Reference permutations — generated by numpy's random.permutation
      (which uses rejection sampling for uniform indices)

We then apply a two-sample test (Kolmogorov-Smirnov or Mann-Whitney)
to determine whether the two distributions differ. This approach is
more rigorous than comparing against theoretical values because it
accounts for finite-sample effects and avoids errors in theoretical
baselines (e.g., E[max|LAT|] for random permutations is ~35, not 16
which is the AES-optimized minimum).

The argument rests on three pillars:
  1. The seed SHA-256(image || b'sbox') is indistinguishable from
     uniform under the random oracle model for SHA-256.
  2. Fisher-Yates with a uniform byte stream produces each
     permutation with equal probability (Knuth, TAOCP Vol. 2).
  3. The modular reduction (j = byte % (i+1)) introduces bias
     at most 1/256 per swap — we test whether this accumulates
     to a detectable level.

Six tests below validate pillars (1)-(3) empirically.

Target: IACR resubmission, Section 4 (Security Analysis).
"""

import hashlib
import numpy as np
import time
import math
from scipy import stats as sp_stats

from bab64_engine import BAB64Config, BabelRenderer, ImageHash

# Activate C extension for speed
try:
    import bab64_fast
    C_ACCEL = bab64_fast.is_available()
except ImportError:
    C_ACCEL = False


# =============================================================================
# S-BOX GENERATION
# =============================================================================

def generate_bab64_sbox(seed_index: int) -> np.ndarray:
    """Generate a BAB64 S-box from a deterministic image seed."""
    config = BAB64Config()
    renderer = BabelRenderer(config)
    seed = hashlib.sha256(f"formal_{seed_index}".encode()).digest()
    image = renderer.render(seed)
    hasher = ImageHash(config)
    return hasher._derive_sbox(image)


def generate_reference_sbox(rng: np.random.Generator) -> np.ndarray:
    """Generate a truly uniform random permutation (rejection sampling)."""
    return rng.permutation(256).astype(np.uint8)


# =============================================================================
# TEST 1 — NIST RANDOMNESS TESTS ON S-BOX OUTPUT SEQUENCES
# =============================================================================
# Rationale: Treat each S-box as a 256-byte sequence and apply runs
# and serial correlation tests. A uniformly random permutation of
# [0..255] has known statistics. Deviations indicate structure.
#
# For a random permutation of n elements:
#   Ascending runs: E = (2n-1)/3, Var = (16n-29)/90  [Knuth, TAOCP §3.3.2]
#   Serial correlation: E[r] = -1/(n-1), Var[r] ≈ 1/n

def count_ascending_runs(sbox: np.ndarray) -> int:
    """Count ascending runs in the sequence."""
    runs = 1
    for i in range(1, len(sbox)):
        if sbox[i] < sbox[i - 1]:
            runs += 1
    return runs


def serial_correlation(sbox: np.ndarray) -> float:
    """Pearson correlation between consecutive S-box entries."""
    x = sbox[:-1].astype(np.float64)
    y = sbox[1:].astype(np.float64)
    return float(np.corrcoef(x, y)[0, 1])


def test_nist_randomness(n_sboxes=1000):
    """
    TEST 1: Runs and serial correlation.
    Two-sample KS test: BAB64 vs reference permutations.
    """
    rng = np.random.default_rng(42)

    bab_runs = []
    ref_runs = []
    bab_corr = []
    ref_corr = []

    for i in range(n_sboxes):
        bab_sb = generate_bab64_sbox(i)
        ref_sb = generate_reference_sbox(rng)

        bab_runs.append(count_ascending_runs(bab_sb))
        ref_runs.append(count_ascending_runs(ref_sb))
        bab_corr.append(serial_correlation(bab_sb))
        ref_corr.append(serial_correlation(ref_sb))

    runs_ks, runs_p = sp_stats.ks_2samp(bab_runs, ref_runs)
    corr_ks, corr_p = sp_stats.ks_2samp(bab_corr, ref_corr)

    return {
        'runs': {
            'bab_mean': np.mean(bab_runs), 'ref_mean': np.mean(ref_runs),
            'ks_stat': runs_ks, 'p_value': runs_p,
        },
        'serial': {
            'bab_mean': np.mean(bab_corr), 'ref_mean': np.mean(ref_corr),
            'ks_stat': corr_ks, 'p_value': corr_p,
        },
    }


# =============================================================================
# TEST 2 — ALGEBRAIC DEGREE (ANF) OF COMPONENT BOOLEAN FUNCTIONS
# =============================================================================
# Rationale: Each 8-bit S-box defines 8 component Boolean functions
# f_i(x) = bit_i(S(x)). The algebraic normal form (ANF) gives the
# unique representation as a polynomial over GF(2). We compare the
# degree distribution of BAB64 vs reference permutations.
#
# Method: Moebius transform to compute ANF, then read off degree.
# Failure mode: if BAB64 consistently shows lower degree, algebraic
# attacks (Courtois-Pieprzyk, 2002) become feasible.

def moebius_transform(truth_table: np.ndarray) -> np.ndarray:
    """Compute ANF via the Moebius transform over GF(2)."""
    n = int(math.log2(len(truth_table)))
    anf = truth_table.copy().astype(np.uint8)
    for i in range(n):
        step = 1 << i
        for j in range(0, 1 << n):
            if j & step:
                anf[j] ^= anf[j ^ step]
    return anf


def algebraic_degree(sbox: np.ndarray) -> list:
    """Compute algebraic degree of each of the 8 component functions."""
    degrees = []
    for bit in range(8):
        tt = np.array([(int(sbox[x]) >> bit) & 1 for x in range(256)],
                      dtype=np.uint8)
        anf = moebius_transform(tt)
        max_deg = 0
        for m in range(256):
            if anf[m]:
                deg = bin(m).count('1')
                if deg > max_deg:
                    max_deg = deg
        degrees.append(max_deg)
    return degrees


def min_algebraic_degree(sbox: np.ndarray) -> int:
    """Minimum algebraic degree across all component functions."""
    return min(algebraic_degree(sbox))


def test_algebraic_degree(n_sboxes=100):
    """
    TEST 2: Algebraic degree — two-sample comparison.
    Mann-Whitney U test on minimum component degree.
    """
    rng = np.random.default_rng(43)

    bab_min_deg = []
    ref_min_deg = []

    for i in range(n_sboxes):
        bab_sb = generate_bab64_sbox(i)
        ref_sb = generate_reference_sbox(rng)
        bab_min_deg.append(min_algebraic_degree(bab_sb))
        ref_min_deg.append(min_algebraic_degree(ref_sb))

    stat, p_value = sp_stats.mannwhitneyu(
        bab_min_deg, ref_min_deg, alternative='two-sided')

    bab_all = []
    ref_all = []
    for i in range(n_sboxes):
        bab_sb = generate_bab64_sbox(i)
        ref_sb = generate_reference_sbox(rng)
        bab_all.extend(algebraic_degree(bab_sb))
        ref_all.extend(algebraic_degree(ref_sb))

    bab_all = np.array(bab_all)
    ref_all = np.array(ref_all)

    return {
        'bab_frac_7': np.mean(bab_all == 7),
        'ref_frac_7': np.mean(ref_all == 7),
        'bab_min_mean': np.mean(bab_min_deg),
        'ref_min_mean': np.mean(ref_min_deg),
        'u_stat': stat,
        'p_value': p_value,
    }


# =============================================================================
# TEST 3 — LINEAR APPROXIMATION TABLE (LAT)
# =============================================================================
# Rationale: LAT[a,b] = #{x : a·x ⊕ b·S(x) = 0} - 128.
# The max |LAT[a,b]| for a,b ≠ 0 determines resistance to linear
# cryptanalysis (Matsui, 1993).
#
# For random permutations of [0..255]:
#   E[max|LAT|] ≈ 2^(n/2) * sqrt(n*ln 2) ≈ 34-38  [O'Connor 1994]
# (NOT 16 — that is the AES-optimized minimum.)
#
# We compare BAB64 vs reference permutations via two-sample KS.

def compute_lat_max_bias(sbox: np.ndarray) -> int:
    """Compute max |bias| in the LAT, excluding trivial row/col 0."""
    n = 256
    max_bias = 0

    # Precompute parity lookup
    parity = np.zeros(n, dtype=np.int32)
    for x in range(n):
        parity[x] = bin(x).count('1') & 1

    for a in range(1, n):
        # Compute a·x for all x
        ax_parity = np.array([parity[a & x] for x in range(n)])
        for b in range(1, n):
            # Compute b·S(x) for all x
            bsx_parity = np.array([parity[b & sbox[x]] for x in range(n)])
            # Count matches
            matches = int(np.sum(ax_parity == bsx_parity))
            bias = abs(matches - 128)
            if bias > max_bias:
                max_bias = bias

    return max_bias


def test_lat(n_sboxes=50):
    """
    TEST 3: LAT max bias — two-sample comparison.
    KS test: BAB64 max_bias distribution vs reference.
    """
    rng = np.random.default_rng(44)

    bab_biases = []
    ref_biases = []

    for i in range(n_sboxes):
        bab_sb = generate_bab64_sbox(i)
        ref_sb = generate_reference_sbox(rng)

        bab_biases.append(compute_lat_max_bias(bab_sb))
        ref_biases.append(compute_lat_max_bias(ref_sb))

        if (i + 1) % 10 == 0:
            print(f"    LAT: {i+1}/{n_sboxes} done", flush=True)

    ks_stat, p_value = sp_stats.ks_2samp(bab_biases, ref_biases)

    return {
        'bab_mean': np.mean(bab_biases),
        'ref_mean': np.mean(ref_biases),
        'bab_std': np.std(bab_biases),
        'ref_std': np.std(ref_biases),
        'ks_stat': ks_stat,
        'p_value': p_value,
    }


# =============================================================================
# TEST 4 — DIFFERENTIAL DISTRIBUTION TABLE (DDT)
# =============================================================================
# Rationale: DDT[Δx, Δy] = #{x : S(x) ⊕ S(x⊕Δx) = Δy}.
# Max DDT entry = differential uniformity. Lower is better.
# For random permutations: E[max DDT] ≈ 10-12 for 8-bit.
# AES: max DDT = 4 (optimal). We compare BAB64 vs reference.

def compute_ddt_max(sbox: np.ndarray) -> int:
    """Compute max entry in the DDT (differential uniformity)."""
    max_val = 0
    for dx in range(1, 256):
        counts = np.zeros(256, dtype=np.int32)
        for x in range(256):
            dy = sbox[x] ^ sbox[x ^ dx]
            counts[dy] += 1
        c = int(np.max(counts))
        if c > max_val:
            max_val = c
    return max_val


def test_ddt(n_sboxes=100):
    """
    TEST 4: DDT max entry — two-sample comparison.
    KS test: BAB64 differential uniformity vs reference.
    """
    rng = np.random.default_rng(45)

    bab_du = []
    ref_du = []

    for i in range(n_sboxes):
        bab_sb = generate_bab64_sbox(i)
        ref_sb = generate_reference_sbox(rng)

        bab_du.append(compute_ddt_max(bab_sb))
        ref_du.append(compute_ddt_max(ref_sb))

        if (i + 1) % 20 == 0:
            print(f"    DDT: {i+1}/{n_sboxes} done", flush=True)

    ks_stat, p_value = sp_stats.ks_2samp(bab_du, ref_du)

    return {
        'bab_mean': np.mean(bab_du),
        'ref_mean': np.mean(ref_du),
        'ks_stat': ks_stat,
        'p_value': p_value,
    }


# =============================================================================
# TEST 5 — FIXED-POINT-FREE FRACTION (DERANGEMENTS)
# =============================================================================
# Rationale: For uniform random permutations of [n]:
#   P(derangement) → 1/e ≈ 0.3679
#   #fixed_points ~ Poisson(1)
#
# The Fisher-Yates modular reduction (j = byte % (i+1)) introduces
# bias. If this accumulates, the fixed-point distribution will shift.
# We compare BAB64 against reference permutations.

def count_fixed_points(sbox: np.ndarray) -> int:
    return int(np.sum(sbox == np.arange(256, dtype=np.uint8)))


def test_fixed_points(n_sboxes=10000):
    """
    TEST 5: Fixed-point distribution — two-sample comparison.
    (a) KS test on fixed-point count distributions.
    (b) Report derangement fractions for both.
    """
    rng = np.random.default_rng(46)

    bab_fp = []
    ref_fp = []

    for i in range(n_sboxes):
        bab_sb = generate_bab64_sbox(i)
        ref_sb = generate_reference_sbox(rng)
        bab_fp.append(count_fixed_points(bab_sb))
        ref_fp.append(count_fixed_points(ref_sb))

    bab_fp = np.array(bab_fp)
    ref_fp = np.array(ref_fp)

    ks_stat, p_value = sp_stats.ks_2samp(bab_fp, ref_fp)

    return {
        'bab_derangement_frac': np.mean(bab_fp == 0),
        'ref_derangement_frac': np.mean(ref_fp == 0),
        'expected_frac': 1.0 / math.e,
        'bab_fp_mean': bab_fp.mean(),
        'ref_fp_mean': ref_fp.mean(),
        'ks_stat': ks_stat,
        'p_value': p_value,
    }


# =============================================================================
# TEST 6 — CYCLE STRUCTURE
# =============================================================================
# Rationale: For a uniform random permutation of [n]:
#   E[#cycles] = H_n ≈ ln(n) + γ ≈ 6.12  for n=256
#   E[longest cycle] ≈ 0.6243 * n ≈ 159.8  (Golomb-Dickman constant)

def decompose_cycles(sbox: np.ndarray) -> list:
    """Decompose permutation into cycle lengths."""
    n = len(sbox)
    visited = np.zeros(n, dtype=bool)
    cycle_lengths = []
    for start in range(n):
        if visited[start]:
            continue
        length = 0
        x = start
        while not visited[x]:
            visited[x] = True
            x = int(sbox[x])
            length += 1
        cycle_lengths.append(length)
    return cycle_lengths


def test_cycle_structure(n_sboxes=1000):
    """
    TEST 6: Cycle structure — two-sample comparison.
    (a) KS test on number of cycles.
    (b) KS test on longest cycle length.
    """
    rng = np.random.default_rng(47)

    bab_num_cycles = []
    ref_num_cycles = []
    bab_longest = []
    ref_longest = []

    for i in range(n_sboxes):
        bab_sb = generate_bab64_sbox(i)
        ref_sb = generate_reference_sbox(rng)

        bab_c = decompose_cycles(bab_sb)
        ref_c = decompose_cycles(ref_sb)

        bab_num_cycles.append(len(bab_c))
        ref_num_cycles.append(len(ref_c))
        bab_longest.append(max(bab_c))
        ref_longest.append(max(ref_c))

    ks_cycles, p_cycles = sp_stats.ks_2samp(bab_num_cycles, ref_num_cycles)
    ks_longest, p_longest = sp_stats.ks_2samp(bab_longest, ref_longest)

    return {
        'bab_mean_cycles': np.mean(bab_num_cycles),
        'ref_mean_cycles': np.mean(ref_num_cycles),
        'ks_cycles': ks_cycles,
        'p_cycles': p_cycles,
        'bab_mean_longest': np.mean(bab_longest),
        'ref_mean_longest': np.mean(ref_longest),
        'ks_longest': ks_longest,
        'p_longest': p_longest,
    }


# =============================================================================
# MAIN — RUN ALL TESTS AND PRINT SUMMARY
# =============================================================================

def run_all():
    print("=" * 72)
    print("  FORMAL ANALYSIS — LEMMA 1: S-BOX INDISTINGUISHABILITY")
    print("  H0: BAB64 S-boxes ~ Uniform(S_256)")
    print("  Method: two-sample tests vs numpy reference permutations")
    print(f"  C acceleration: {'ENABLED' if C_ACCEL else 'DISABLED'}")
    print("=" * 72)
    print()

    alpha = 0.01
    results = []

    def judge(p):
        return "PASS" if p > alpha else "FAIL"

    # --- TEST 1: NIST Randomness ---
    print("  [1/6] NIST Randomness Tests (1,000 S-boxes)...")
    t0 = time.time()
    r1 = test_nist_randomness(1000)
    dt = time.time() - t0
    print(f"         Runs — BAB64: {r1['runs']['bab_mean']:.1f}, "
          f"Ref: {r1['runs']['ref_mean']:.1f}")
    print(f"         Serial corr — BAB64: {r1['serial']['bab_mean']:.5f}, "
          f"Ref: {r1['serial']['ref_mean']:.5f}")
    print(f"         Done in {dt:.1f}s")

    results.append(("1a. Ascending runs (KS)",
                     f"D={r1['runs']['ks_stat']:.4f}",
                     r1['runs']['p_value']))
    results.append(("1b. Serial correlation (KS)",
                     f"D={r1['serial']['ks_stat']:.4f}",
                     r1['serial']['p_value']))

    # --- TEST 2: Algebraic Degree ---
    print("  [2/6] Algebraic Degree Analysis (100 S-boxes)...")
    t0 = time.time()
    r2 = test_algebraic_degree(100)
    dt = time.time() - t0
    print(f"         Deg 7 — BAB64: {r2['bab_frac_7']*100:.1f}%, "
          f"Ref: {r2['ref_frac_7']*100:.1f}%")
    print(f"         Done in {dt:.1f}s")

    results.append(("2. Min algebraic degree (MW-U)",
                     f"U={r2['u_stat']:.0f}",
                     r2['p_value']))

    # --- TEST 3: LAT ---
    print("  [3/6] Linear Approximation Table (50 S-boxes)...")
    t0 = time.time()
    r3 = test_lat(50)
    dt = time.time() - t0
    print(f"         Max bias — BAB64: {r3['bab_mean']:.1f}±{r3['bab_std']:.1f}, "
          f"Ref: {r3['ref_mean']:.1f}±{r3['ref_std']:.1f}")
    print(f"         Done in {dt:.1f}s")

    results.append(("3. LAT max bias (KS)",
                     f"D={r3['ks_stat']:.4f}",
                     r3['p_value']))

    # --- TEST 4: DDT ---
    print("  [4/6] Differential Distribution Table (100 S-boxes)...")
    t0 = time.time()
    r4 = test_ddt(100)
    dt = time.time() - t0
    print(f"         Diff unif — BAB64: {r4['bab_mean']:.1f}, "
          f"Ref: {r4['ref_mean']:.1f}")
    print(f"         Done in {dt:.1f}s")

    results.append(("4. DDT max entry (KS)",
                     f"D={r4['ks_stat']:.4f}",
                     r4['p_value']))

    # --- TEST 5: Fixed Points ---
    print("  [5/6] Fixed-Point Distribution (10,000 S-boxes)...")
    t0 = time.time()
    r5 = test_fixed_points(10000)
    dt = time.time() - t0
    print(f"         Derangements — BAB64: {r5['bab_derangement_frac']:.4f}, "
          f"Ref: {r5['ref_derangement_frac']:.4f}, "
          f"Theory: {r5['expected_frac']:.4f}")
    print(f"         FP mean — BAB64: {r5['bab_fp_mean']:.3f}, "
          f"Ref: {r5['ref_fp_mean']:.3f}")
    print(f"         Done in {dt:.1f}s")

    results.append(("5. Fixed-point count (KS)",
                     f"D={r5['ks_stat']:.4f}",
                     r5['p_value']))

    # --- TEST 6: Cycle Structure ---
    print("  [6/6] Cycle Structure Analysis (1,000 S-boxes)...")
    t0 = time.time()
    r6 = test_cycle_structure(1000)
    dt = time.time() - t0
    print(f"         #Cycles — BAB64: {r6['bab_mean_cycles']:.2f}, "
          f"Ref: {r6['ref_mean_cycles']:.2f}")
    print(f"         Longest — BAB64: {r6['bab_mean_longest']:.1f}, "
          f"Ref: {r6['ref_mean_longest']:.1f}")
    print(f"         Done in {dt:.1f}s")

    results.append(("6a. #Cycles (KS)",
                     f"D={r6['ks_cycles']:.4f}",
                     r6['p_cycles']))
    results.append(("6b. Longest cycle (KS)",
                     f"D={r6['ks_longest']:.4f}",
                     r6['p_longest']))

    # --- SUMMARY TABLE ---
    print()
    print("=" * 72)
    print("  SUMMARY — LEMMA 1: S-BOX INDISTINGUISHABILITY")
    print(f"  Two-sample tests: BAB64 vs uniform random permutations")
    print(f"  Significance level alpha = {alpha}")
    print("=" * 72)
    hdr = f"  {'Test':<38} {'Statistic':<22} {'p-value':>8} {'Result':>6}"
    sep = f"  {'-'*38} {'-'*22} {'-'*8} {'-'*6}"
    print(hdr)
    print(sep)

    all_pass = True
    for name, stat, p in results:
        verdict = judge(p)
        if verdict == "FAIL":
            all_pass = False
        print(f"  {name:<38} {stat:<22} {p:>8.4f} {verdict:>6}")

    print(sep)

    if all_pass:
        print()
        print("  CONCLUSION: All tests PASS at alpha=0.01.")
        print("  We FAIL TO REJECT H0: BAB64 S-boxes are")
        print("  indistinguishable from uniform random permutations")
        print("  across all six statistical criteria.")
        print()
        print("  FORMAL ARGUMENT FOR PAPER:")
        print("  Under the random oracle model for SHA-256, the seed")
        print("  SHA-256(image || b'sbox') is uniformly distributed.")
        print("  Fisher-Yates shuffle with this seed produces each")
        print("  permutation with probability 1/256! + epsilon, where")
        print("  epsilon is bounded by the modular bias (at most")
        print("  255 * 1/256 < 1 per permutation). Empirical testing")
        print("  across six structural criteria confirms that this")
        print("  bias is statistically undetectable at n=10,000.")
    else:
        failed = [(name, p) for name, _, p in results if p <= alpha]
        print()
        print(f"  WARNING: {len(failed)} test(s) FAILED at alpha={alpha}:")
        for name, p in failed:
            print(f"    - {name} (p={p:.6f})")
        print()
        print("  The Fisher-Yates modular bias (j = byte % (i+1))")
        print("  may be accumulating to a detectable level. Consider")
        print("  switching to rejection sampling for index generation")
        print("  if formal indistinguishability is required.")
        print()
        print("  NOTE: Failing against reference permutations means")
        print("  the deviation is NOT due to incorrect baselines —")
        print("  BAB64 S-boxes genuinely differ from uniform.")

    print()
    print("=" * 72)


if __name__ == "__main__":
    run_all()
